Settings:
      # Scheduler Interval in minutes
      Interval: 5
      # true: random | false: consecutive
      Random: false
      # true: permissions security | false: only OP's
      Permission: true
Announcer:
      # Strings to announce
      Strings:
            - '&RED;Running CraftBukkit server with &GOLD;AutoAnnouncer.'
            - '&GREEN;Development by Sharkiller!'