name: AutoAnnouncer
main: ar.com.sharkale.AutoAnnouncer.AutoAnnouncer
version: 1.0-04.08
author: Sharkiller
description: Global announcements every few minutes. 
commands:
  announcer:
    description: Manage announce
    usage: /<command> help - Help for AutoAnnouncer